sudo: false
language: python

python:
  - "3.5"
  - "3.4"

env:
  - DJANGO="django==1.10.4"


install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pep8
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."

script: coverage run --source=geoware manage.py test

after_success:
  coveralls
