#!/bin/bash

# Ignoring autogenerated files
#  -- Migration directories
# Ignoring error codes
#  -- E128 continuation line under-indented for visual indent
#  -- E225 missing whitespace around operator
#  -- E501 line too long
#  -- E203 whitespace before ':'

pep8 --exclude=migrations --ignore=E128,E203,E225,E501 .
