from django.utils.translation import ugettext as _

GEOWARE_LANGUAGE_CHOICES = (
    ('af', _('Afrikaans')),
    ('af-ZA', _('Afrikaans (South Africa)')),
    ('ar', _('Arabic')),
    ('ar-AE', _('Arabic (UAE)')),
    ('ar-BH', _('Arabic (Bahrain)')),
    ('ar-DZ', _('Arabic (Algeria)')),
    ('ar-EG', _('Arabic (Egypt)')),
    ('ar-IQ', _('Arabic (Iraq)')),
    ('ar-JO', _('Arabic (Jordan)')),
    ('ar-KW', _('Arabic (Kuwait)')),
    ('ar-LB', _('Arabic (Lebanon)')),
    ('ar-LY', _('Arabic (Libya)')),
    ('ar-MA', _('Arabic (Morocco)')),
    ('ar-OM', _('Arabic (Oman)')),
    ('ar-QA', _('Arabic (Qatar)')),
    ('ar-SA', _('Arabic (Saudi Arabia)')),
    ('ar-SY', _('Arabic (Syria)')),
    ('ar-TN', _('Arabic (Tunisia)')),
    ('ar-YE', _('Arabic (Yemen)')),
    ('az', _('Azeri')),
    ('az-AZ', _('Azeri (Azerbaijan)')),
    ('be', _('Belarusian')),
    ('be-BY', _('Belarusian (Belarus)')),
    ('bg', _('Bulgarian')),
    ('bg-BG', _('Bulgarian (Bulgaria)')),
    ('bs-BA', _('Bosnian (Bosnia and Herzegovina)')),
    ('ca', _('Catalan')),
    ('ca-ES', _('Catalan (Spain)')),
    ('cs', _('Czech')),
    ('cs-CZ', _('Czech (Czech Republic)')),
    ('cy', _('Welsh')),
    ('cy-GB', _('Welsh (United Kingdom)')),
    ('da', _('Danish')),
    ('da-DK', _('Danish (Denmark)')),
    ('de', _('German')),
    ('de-AT', _('German (Austria)')),
    ('de-CH', _('German (Switzerland)')),
    ('de-DE', _('German (Germany)')),
    ('de-LI', _('German (Liechtenstein)')),
    ('de-LU', _('German (Luxembourg)')),
    ('dv', _('Divehi')),
    ('dv-MV', _('Divehi (Maldives)')),
    ('el', _('Greek')),
    ('el-GR', _('Greek (Greece)')),
    ('en', _('English')),
    ('en-AU', _('English (Australia)')),
    ('en-BZ', _('English (Belize)')),
    ('en-CA', _('English (Canada)')),
    ('en-CB', _('English (Caribbean)')),
    ('en-GB', _('English (United Kingdom)')),
    ('en-IE', _('English (Ireland)')),
    ('en-JM', _('English (Jamaica)')),
    ('en-NZ', _('English (New Zealand)')),
    ('en-PH', _('English (The Philippines)')),
    ('en-TT', _('English (Trinidad and Tobago)')),
    ('en-US', _('English (United States)')),
    ('en-VC', _('English (Saint Vincent and the Grenadines)')),
    ('en-VG', _('English (British Virgin Islands)')),
    ('en-ZA', _('English (South Africa)')),
    ('en-ZW', _('English (Zimbabwe)')),
    ('eo', _('Esperanto')),
    ('es', _('Spanish')),
    ('es-AR', _('Spanish (Argentina)')),
    ('es-BO', _('Spanish (Bolivia)')),
    ('es-CL', _('Spanish (Chile)')),
    ('es-CO', _('Spanish (Colombia)')),
    ('es-CR', _('Spanish (Costa Rica)')),
    ('es-DO', _('Spanish (Dominican Republic)')),
    ('es-EC', _('Spanish (Ecuador)')),
    ('es-ES', _('Spanish (Castilian)')),
    ('es-ES', _('Spanish (Spain)')),
    ('es-GT', _('Spanish (Guatemala)')),
    ('es-HN', _('Spanish (Honduras)')),
    ('es-MX', _('Spanish (Mexico)')),
    ('es-NI', _('Spanish (Nicaragua)')),
    ('es-PA', _('Spanish (Panama)')),
    ('es-PE', _('Spanish (Peru)')),
    ('es-PR', _('Spanish (Puerto Rico)')),
    ('es-PY', _('Spanish (Paraguay)')),
    ('es-SV', _('Spanish (El Salvador)')),
    ('es-UY', _('Spanish (Uruguay)')),
    ('es-VE', _('Spanish (Venezuela)')),
    ('et', _('Estonian')),
    ('et-EE', _('Estonian (Estonia)')),
    ('eu', _('Basque')),
    ('eu-ES', _('Basque (Spain)')),
    ('fa', _('Farsi')),
    ('fa-IR', _('Farsi (Iran)')),
    ('fi', _('Finnish')),
    ('fi-FI', _('Finnish (Finland)')),
    ('fo', _('Faroese')),
    ('fo-FO', _('Faroese (Faroe Islands)')),
    ('fr', _('French')),
    ('fr-BE', _('French (Belgium)')),
    ('fr-CA', _('French (Canada)')),
    ('fr-CH', _('French (Switzerland)')),
    ('fr-FR', _('French (France)')),
    ('fr-LU', _('French (Luxembourg)')),
    ('fr-MC', _('French (Monaco)')),
    ('fr-WF', _('French (Futuna)')),
    ('fud', _('Futunian (Futuna)')),
    ('gl', _('Galician')),
    ('gl-ES', _('Galician (Spain)')),
    ('gu', _('Gujarati')),
    ('gu-IN', _('Gujarati (India)')),
    ('he', _('Hebrew')),
    ('he-IL', _('Hebrew (Israel)')),
    ('hi', _('Hindi')),
    ('hi-IN', _('Hindi (India)')),
    ('hr', _('Croatian')),
    ('hr-BA', _('Croatian (Bosnia and Herzegovina)')),
    ('hr-HR', _('Croatian (Croatia)')),
    ('hu', _('Hungarian')),
    ('hu-HU', _('Hungarian (Hungary)')),
    ('hy', _('Armenian')),
    ('hy-AM', _('Armenian (Armenia)')),
    ('id', _('Indonesian')),
    ('id-ID', _('Indonesian (Indonesia)')),
    ('is', _('Icelandic')),
    ('is-IS', _('Icelandic (Iceland)')),
    ('it', _('Italian')),
    ('it-CH', _('Italian (Switzerland)')),
    ('it-IT', _('Italian (Italy)')),
    ('ja', _('Japanese')),
    ('ja-JP', _('Japanese (Japan)')),
    ('ka', _('Georgian')),
    ('ka-GE', _('Georgian (Georgia)')),
    ('kk', _('Kazakh')),
    ('kk-KZ', _('Kazakh (Kazakhstan)')),
    ('kn', _('Kannada')),
    ('kn-IN', _('Kannada (India)')),
    ('ko', _('Korean')),
    ('ko-KR', _('Korean (Korea)')),
    ('kok', _('Konkani')),
    ('kok-IN', _('Konkani (India)')),
    ('ky', _('Kyrgyz')),
    ('ky-KG', _('Kyrgyz (Kyrgyzstan)')),
    ('lt', _('Lithuanian')),
    ('lt-LT', _('Lithuanian (Lithuania)')),
    ('lv', _('Latvian')),
    ('lv-LV', _('Latvian (Latvia)')),
    ('mi', _('Maori')),
    ('mi-NZ', _('Maori (New Zealand)')),
    ('mk', _('Macedonian')),
    ('mk-MK', _('Macedonian (Republic of Macedonia)')),
    ('mn', _('Mongolian')),
    ('mn-MN', _('Mongolian (Mongolia)')),
    ('mr', _('Marathi')),
    ('mr-IN', _('Marathi (India)')),
    ('ms', _('Malay')),
    ('ms-BN', _('Malay (Brunei Darussalam)')),
    ('ms-MY', _('Malay (Malaysia)')),
    ('mt', _('Maltese')),
    ('mt-MT', _('Maltese (Malta)')),
    ('nb', _('Norwegian Bokmal')),
    ('nb-NO', _('Norwegian Bokmal (Norway)')),
    ('nl', _('Dutch')),
    ('nl-BE', _('Dutch (Belgium)')),
    ('nl-NL', _('Dutch (Netherlands)')),
    ('nn-NO', _('Norwegian Nynorsk (Norway)')),
    ('ns', _('Northern Sotho')),
    ('ns-ZA', _('Northern Sotho (South Africa)')),
    ('pa', _('Punjabi')),
    ('pa-IN', _('Punjabi (India)')),
    ('pl', _('Polish')),
    ('pl-PL', _('Polish (Poland)')),
    ('ps', _('Pashto')),
    ('ps-AR', _('Pashto (Afghanistan)')),
    ('pt', _('Portuguese')),
    ('pt-BR', _('Portuguese (Brazil)')),
    ('pt-PT', _('Portuguese (Portugal)')),
    ('qu', _('Quechua')),
    ('qu-BO', _('Quechua (Bolivia)')),
    ('qu-EC', _('Quechua (Ecuador)')),
    ('qu-PE', _('Quechua (Peru)')),
    ('ro', _('Romanian')),
    ('ro-RO', _('Romanian (Romania)')),
    ('ru', _('Russian')),
    ('ru-RU', _('Russian (Russia)')),
    ('sa', _('Sanskrit')),
    ('sa-IN', _('Sanskrit (India)')),
    ('se', _('Sami (Northern)')),
    ('se-FI', _('Sami (Finland)')),
    ('se-NO', _('Sami (Norway)')),
    ('se-SE', _('Sami (Sweden)')),
    ('sk', _('Slovak')),
    ('sk-SK', _('Slovak (Slovakia)')),
    ('sl', _('Slovenian')),
    ('sl-SI', _('Slovenian (Slovenia)')),
    ('sq', _('Albanian')),
    ('sq-AL', _('Albanian (Albania)')),
    ('sr-BA', _('Serbian (Bosnia and Herzegovina)')),
    ('sr-SP', _('Serbian (Serbia and Montenegro)')),
    ('sv', _('Swedish')),
    ('sv-FI', _('Swedish (Finland)')),
    ('sv-SE', _('Swedish (Sweden)')),
    ('sw', _('Swahili')),
    ('sw-KE', _('Swahili (Kenya)')),
    ('syr', _('Syriac')),
    ('syr-SY', _('Syriac (Syria)')),
    ('ta', _('Tamil')),
    ('ta-IN', _('Tamil (India)')),
    ('te', _('Telugu')),
    ('te-IN', _('Telugu (India)')),
    ('th', _('Thai')),
    ('th-TH', _('Thai (Thailand)')),
    ('tl', _('Tagalog')),
    ('tl-PH', _('Tagalog (The Philippines)')),
    ('tn', _('Tswana')),
    ('tn-ZA', _('Tswana (South Africa)')),
    ('tr', _('Turkish')),
    ('tr-TR', _('Turkish (Turkey)')),
    ('tt', _('Tatar')),
    ('tt-RU', _('Tatar (Russia)')),
    ('ts', _('Tsonga')),
    ('uk', _('Ukrainian')),
    ('uk-UA', _('Ukrainian (Ukraine)')),
    ('ur', _('Urdu')),
    ('ur-PK', _('Urdu (Pakistan)')),
    ('uz', _('Uzbek (Latin)')),
    ('uz-UZ', _('Uzbek (Uzbekistan)')),
    ('vi', _('Vietnamese')),
    ('vi-VN', _('Vietnamese (Viet Nam)')),
    ('wls', _('Wallisian (Noumea)')),
    ('xh', _('Xhosa')),
    ('xh-ZA', _('Xhosa (South Africa)')),
    ('zh', _('Chinese')),
    ('zh-CN', _('Chinese (Simplified)')),
    ('zh-HK', _('Chinese (Hong Kong)')),
    ('zh-MO', _('Chinese (Macau)')),
    ('zh-SG', _('Chinese (Singapore)')),
    ('zh-TW', _('Chinese (Traditional)')),
    ('zu', _('Zulu')),
    ('zu-ZA', _('Zulu (South Africa)')),
)
