# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ocean',
            name='name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('fips', 'country')]),
        ),
    ]
