# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='sister',
        ),
        migrations.AddField(
            model_name='city',
            name='district_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoware.City', verbose_name='LOCATION.CITY.DISTRICT_OF'),
        ),
    ]
