# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0002_auto_20170106_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_std',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LOCATION.NAME_STD.FIELD'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name_std',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LOCATION.NAME_STD.FIELD'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_std',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LOCATION.NAME_STD.FIELD'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_std',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LOCATION.NAME_STD.FIELD'),
        ),
        migrations.AlterField(
            model_name='ocean',
            name='name_std',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LOCATION.NAME_STD.FIELD'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_std',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LOCATION.NAME_STD.FIELD'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='name_std',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='LOCATION.NAME_STD.FIELD'),
        ),
    ]
