# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0003_auto_20170106_2257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('fips', 'name_std', 'country')]),
        ),
    ]
