# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0003_auto_20170112_2037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='district',
            name='altnames',
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
