# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0004_auto_20170106_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subregion',
            unique_together=set([('name', 'fips', 'region')]),
        ),
    ]
