# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0004_auto_20170112_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='elevation',
            field=models.IntegerField(default=0, verbose_name='LOCATION.ELEVATION_METERS'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='elevation',
            field=models.IntegerField(default=0, verbose_name='LOCATION.ELEVATION_METERS'),
        ),
        migrations.AlterField(
            model_name='country',
            name='elevation',
            field=models.IntegerField(default=0, verbose_name='LOCATION.ELEVATION_METERS'),
        ),
        migrations.AlterField(
            model_name='ocean',
            name='elevation',
            field=models.IntegerField(default=0, verbose_name='LOCATION.ELEVATION_METERS'),
        ),
        migrations.AlterField(
            model_name='region',
            name='elevation',
            field=models.IntegerField(default=0, verbose_name='LOCATION.ELEVATION_METERS'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='elevation',
            field=models.IntegerField(default=0, verbose_name='LOCATION.ELEVATION_METERS'),
        ),
    ]
