# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0005_auto_20170106_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('name', 'code')]),
        ),
    ]
