# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0005_auto_20170112_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altname',
            name='is_preferred',
        ),
        migrations.RemoveField(
            model_name='altname',
            name='is_short',
        ),
    ]
