# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0006_auto_20170113_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altname',
            name='ref_geoname_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
