# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0007_auto_20170113_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='absolute_url',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='absolute_url',
        ),
        migrations.RemoveField(
            model_name='country',
            name='absolute_url',
        ),
        migrations.RemoveField(
            model_name='ocean',
            name='absolute_url',
        ),
        migrations.RemoveField(
            model_name='region',
            name='absolute_url',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='absolute_url',
        ),
        migrations.AlterField(
            model_name='city',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='LOCATION.INFO_DETAILS'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='LOCATION.INFO_DETAILS'),
        ),
        migrations.AlterField(
            model_name='country',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='LOCATION.INFO_DETAILS'),
        ),
        migrations.AlterField(
            model_name='ocean',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='LOCATION.INFO_DETAILS'),
        ),
        migrations.AlterField(
            model_name='region',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='LOCATION.INFO_DETAILS'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='LOCATION.INFO_DETAILS'),
        ),
    ]
