# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0008_auto_20170113_0029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('code',)]),
        ),
    ]
