# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'verbose_name': 'Subdivision', 'verbose_name_plural': 'Subdivisions'},
        ),
        migrations.AlterField(
            model_name='city',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoware_city_division', to='geoware.Division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='city',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoware_city_subdivision', to='geoware.Subdivision', verbose_name='Subdivision'),
        ),
        migrations.AlterField(
            model_name='division',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoware_division_capital', to='geoware.City', verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='division',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoware_division_country', to='geoware.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='division',
            name='fips',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='FIPS Code'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoware_subdivision_capital', to='geoware.City', verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geoware_subdivision_country', to='geoware.Division', verbose_name='Division'),
        ),
    ]
